### ISSUE TITLE
Picture object

### ISSUE THREAD

**Issue by DrAirRock** [quuu/ASCIImage#7]
- [x] Object that takes in Ascii array 
- [x] Stores the data in a way that members are easily indexed and retired
- [x] Keep track of char per row 

* At this point would It make more sense to store everything as a list, and have an array of lists. 
- [x] Discuss

**Comment by quuu** [comment]
Created picture class, created seed class to use as temp storage for greyscale values

Going to store many pictures in a list for easy index

**Comment by quuu** [comment]
Removed Seed, just a picture with a 1d array split with \n's

Also stores height and width
