### ISSUE TITLE
Population Generator 

### ISSUE THREAD

**Issue by DrAirRock** [quuu/ASCIImage#8]
- [x] On first go everything is random will generate N members of population 
- [ ] On all other runs will take half the data from each of the parents and generate N members using the mutation function. 
- [ ] Population length and width will be the same as the target image

**Comment by quuu** [comment]
Initial random generation is done

**Comment by quuu** [comment]
First run of next generation will be splicing half of one and half of the other parent to avoid undermining performance too much
